language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
    provider: heroku
    app: project1-travis-alex-apostol
    on: master
    skip_cleanup: true
    api_key:
    secure: K8LpjRHRptM6a0TW586K63oaLtk6H1V0+AaRVr5S86kKufLbd82pf+74vLFfK5LJlZNxCjxAKDU6ug5p5q6ekwkKQP7YPkIqrFJZpWKItgzGhe3Ve8N0/lSu/2RQ7cdnEarw3HQDRIu7MgOe76MZD1K93zWKqx52tqezICkG/m1o5qgScb1bjUC0srALqq2ya+Nsgzy4/QLxSLwpRtnnBV5Gk4X+8I5eIycukg9yopOGeUPco6ERc2XrS+LbJ5CQZFljSOGAAB6EI9HM5LyVQ3JUM2UKUeUqvJPZttNgVkPgXg1JDwCEbdLQPcAdm7F0XdUDoF7IpRxbf9+Tj/GrUoenKFoFv4gfHi0Gtb+klE1ynMozkg2ZJLzjlHstTkSoj8nf43Ud+/iKHVOngcBCpJkGQ2qTZf+6pXVM4uFytfTeaTPBNTPiPosdkiLuwml27o0/ZPrlQ/xtR41HIzeYkVCb8V8z6RmzcGY3t6kPiiPm38OWNZyzEKgrhs24ZK/a+VkysGsqz+n/r2sm/mQMZE/8ypdOPiVBtt9uWY+uI/0wid68COhJblX5nloKNbfZEsf9Hpx90/wDAoRlzKE6l+BPILrjCYCfAmXMEzpvWDEGGvQh+bxoDM5ZMS1BiDL6cabvuzrpQl+0qZrTiGuYz684zEvl7hAP8o5dMvA9Hfc=
