language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
    provider: heroku
    app: project1-travis-alex-apostol
    on: master
    skip_cleanup: true
    api_key:
    	secure: BWC/SIFVuOn8OUBFmae5CI6ZqMvBBPfNU7dg0PNuSi7Xkj66y2zQ1vbMtQ/vnmYuoEJNg22dmRutYcubtfwboKUF6DcjBYcNI5BRpabEMh1dAuvw6gyv62wJzriXXCjMHBBGckXw5/waPpFkvN3JK8l7i/W0KFo1FH2xSOH2DnfjZJFFTCXRJbGLFZtUkS8wIcM4C7Uc2YjtHaeHm3Eu/Cl/k0B05v1zzZSsO+0IjeXAFXtRwGVENTjUReEoLYtWuCr6TVpatZU2GU7tRHGuvpA9JNZABU7SCsQXa5n0+MPn2nKApsYuuSTtq3EZurFv+kXTDw8LpA+OCJqTIdBPypWjkw+Ny8gi0khCRzJzQDPJAsuoW3TXbR7ic+rPZ5YxEqqbrGEOjKb+cdp/tds4Qs22/ZjImkf5DqMLtXCt6HLe7CXdfm9YE/mW+B1ABqiTsenBqjtzmhxPBLERSFFMwRU0ESRVA0Q5cmKx1JbNaxExNH5q76cm0vKU+bFPNwmKscQ1YQj68Ui0+MxpcDUjWomY5lSrUl5TRR+6M1Lz/oluoC3mibHThDTEv++c3Eu9iazjFZbVVYXHGUf8FYzTBbZI78u18sf8jcfhleR4tKhkUjTBKHxHXzfY9W9KrpfNvkMCInXIEsb1Qy/1ijxyosfsKP6wXt3jgDHa49nMamo=
